/**
 * en-US only: replaces the Korean *sample sentences* embedded in the Deep Essence
 * prompts (examples, "BAD/GOOD" illustrations and forbidden-phrase lists that sit
 * right beside user-facing output fields) with natural English equivalents, so
 * the en-US model never sees Korean prose next to the fields it must fill in.
 *
 * ko-KR prompts never pass through this function and are unchanged.
 *
 * Deliberately left as-is (canonical / internal Saju source terms, safe because
 * the prompt tells the model never to write them): bare terms such as 도화살,
 * 현침살, 천을귀인, 십신, 격국, 용신, 귀문, 합/충/형/파/해.
 *
 * Replacement is exact-substring, longest key first.
 */
const EN_EXAMPLES: Array<[string, string]> = [
  // whole-sentence keys (longest-first ordering makes these win over the fragments below)
  ["앞으로 중요한 선택을 앞두고, ___ 한 환경을 우선 선택하고, ___ 한 상황은 되도록 피하는 것을 하나의 판단 기준으로 삼을 수 있어요", "When you face an important choice, prefer ___ environments, avoid ___ situations where you can, and let that be your one decision criterion"],
  ["겉으로는 A처럼 보이지만 가까워지면 B", "looks like A on the surface but turns into B up close"],
  ["잘 맞춰주는 것처럼 보여도 자기 기준 C가 분명함", "seems accommodating, yet has a clear standard of their own (C)"],
  ["단단해 보이지만 안전한 관계에서는 D 표현이 커짐", "looks firm, but D expression grows in safe relationships"],
  ["나는 원래 A가 자연스럽다 -> 하지만 현실에서는 B를 더 많이 사용하게 되었다 -> 그래서 C라는 능력이 발달했다 -> 다만 그 방식을 계속 유지할 때 D라는 에너지가 든다.", "I'm naturally comfortable with A -> but in real life I use B more -> so the capability C developed -> but keeping that up takes energy D."],
  // ── titles / fuels / drains (strengths, watchouts, energy) ──
  ["말보다 먼저 분위기를 읽는 힘", "reading the room before anyone says a word"],
  ["공감 능력/완벽주의", "empathy/perfectionism"],
  ["중요한 결정에서 다른 사람의 확신을 먼저 확인하는 방식", "checking other people's certainty first on important decisions"],
  ["의존성/완벽주의/불안정함", "dependence/perfectionism/instability"],
  ["내 의도를 길게 설명하지 않아도 통하는 대화", "conversations where my intent lands without a long explanation"],
  ["여러 사람의 기대를 동시에 맞춰야 하는 상황", "situations where I have to meet several people's expectations at once"],

  // ── layered identity ──
  ["쉽게 신뢰를 주는 첫인상", "a first impression that easily earns trust"],
  ["가까워질수록 세심해지는 방식", "getting more attentive the closer people get"],
  ["안전한 관계에서 더 솔직해지는 면", "being more candid in safe relationships"],
  ["혼자 결정할 수 있어야 편한 깊은 욕구", "a deep need to be able to decide alone"],
  ["자유로운 영혼, 배려 깊은 친구, 좋은 사람, 따뜻한 사람, 리더, 공감형, 독립적인 사람", "free spirit, caring friend, good person, warm person, leader, empath type, independent person"],
  ["진짜/진정한/찐", "real/true/authentic"],
  ["나/모습/자아", "me/face/self"],
  ["진정한 나, 진짜 나, 진짜 모습, 진정한 모습, 본모습", "the true you, the real you, your real face, your true face, your true colors"],
  ["진정한 나", "the true you"],
  ["진짜 나", "the real you"],
  ["가짜 나", "the fake you"],
  ["차분해 보여요", "comes across as calm"],
  ["사실은 따뜻한 사람이에요", "is actually a warm person"],
  ["엄격하게 구획하는 모습", "a strictly compartmentalizing demeanor"],
  ["자율적 결실", "autonomous fruition"],
  ["자연스러운 방어 방식", "a natural defense style"],
  ["타인의 개입을 자제시키는 편", "tends to hold others' involvement at bay"],
  ["외부 표준에 따른 수행 압박", "pressure to perform to external standards"],
  ["가까울수록 오히려 내 공간이 더 분명해지는 사람", "someone whose own space gets clearer the closer people get"],
  ["남이 납득하는 것보다 내가 납득해야 움직이는 사람", "someone who moves only once they themselves are convinced, not when others are"],
  ["겉으로는", "on the surface"],
  ["처럼 보이지만 가까워지면", "but up close"],
  ["잘 맞춰주는 것처럼 보여도 자기 기준", "seems accommodating, yet their own standard"],
  ["가 분명함", "is clear"],
  ["단단해 보이지만 안전한 관계에서는", "looks firm, but in a safe relationship"],
  ["표현이 커짐", "expression grows"],
  ["타인 고려, 자율성, 안정감", "consideration of others, autonomy, stability"],
  ["~하세요, ~해보세요, ~하는 것이 중요해요, ~할 필요가 있어요, ~기억하세요, ~조심하세요", "'you should…', 'try to…', 'it's important to…', 'you need to…', 'remember to…', 'be careful to…'"],
  ["중요한 결정을 앞두고", "when facing an important decision"],
  ["관계의 분위기를 읽어야 할 때", "when you have to read the mood of a relationship"],
  ["친구가 힘들어할 때", "when a friend is struggling"],
  ["새 직장에서", "at a new job"],
  ["훌륭해요", "you're wonderful"],
  ["매력적이에요", "you're so attractive"],
  ["사랑받아요", "people love you"],
  ["서로 다른 모습이 아니라, 거리에 따라 드러나는 순서가 다른 것이다", "not different people, but a different order of what shows up at each distance"],
  ["처음에는 차분하고, 친해지면 다정하고, 가까우면 자유로워요.", "At first you're calm, once close you're warm, and when very close you're free."],
  [
    "처음에는 감정을 크게 드러내지 않아 안정적인 사람으로 읽힐 수 있지만, 신뢰가 쌓이면 관계를 세심하게 읽고 반응하는 면이 더 분명해져요. 아주 가까운 관계에서 더 자유롭게 보이는 것은 처음의 모습이 가짜여서가 아니라, 안전하다고 느낄수록 스스로를 조절할 필요가 줄어들기 때문일 수 있습니다.",
    "At first you don't show much emotion, so you can read as steady, but once trust builds, the way you read and respond to people carefully becomes clearer. Seeming freer in very close relationships isn't because the first impression was fake; it may simply be that the safer you feel, the less you need to regulate yourself.",
  ],

  // ── strengths / watchouts ──
  ["의존성", "dependence"],
  ["불안정함", "instability"],
  ["완벽주의자다", "is a perfectionist"],
  ["완벽주의", "perfectionism"],
  ["통제욕", "need for control"],
  ["권력욕", "hunger for power"],
  ["회피형", "avoidant type"],
  ["의존적이다", "is dependent"],
  ["불안정하다", "is unstable"],
  ["독단적이다", "is dogmatic"],
  ["감정적이다", "is emotional"],
  ["중요한 결정일수록 다른 사람의 확신을 먼저 확인하는 방식", "checking other people's certainty first, the more important the decision"],
  ["충분히 잘하고 있어도 기준을 쉽게 낮추지 않는 방식", "not easily lowering your standard even when you're already doing well"],
  ["~하는 상황에서", "in situations where…"],
  ["~하는 경향이 나타날 수 있어요", "a tendency to … can show up"],
  ["~할수록 더 많은 에너지를 쓸 수 있어요", "the more you …, the more energy it can take"],
  ["~를 먼저 확인하는 방식이 익숙할 수 있어요", "checking … first can feel familiar"],
  ["내가 자연스럽게 잘 쓰는 힘", "The strengths I use naturally"],
  ["공감 능력", "empathy"],
  ["잘하지만 오래 쓰면 지치는 방식", "Things I do well but that wear me out when overused"],
  [
    "주변의 관점을 잘 고려하는 능력은 큰 장점이지만, 중요한 결정에서도 계속 모든 사람의 반응을 확인해야만 안심이 된다면 결정보다 확인 과정에 더 많은 에너지를 쓰게 됩니다",
    "Being good at weighing other people's views is a real strength, but if you can only feel settled after checking everyone's reaction even on big decisions, you end up spending more energy on checking than on deciding",
  ],
  ["쉬세요", "get some rest"],
  ["자신을 돌보세요", "take care of yourself"],
  ["마음을 비우세요", "clear your mind"],
  ["새로운 직장에 들어갔을 때", "when you started a new job"],
  ["팀 프로젝트에서", "in a team project"],
  ["상사와 이야기할 때", "when talking to your boss"],
  ["가족 문제에서", "in a family matter"],
  ["여러 사람의 기대를 동시에 고려할 때", "when weighing several people's expectations at once"],
  ["관계의 분위기를 계속 읽어야 할 때", "when you have to keep reading the mood of a relationship"],
  ["예측하기 어려운 상황이 길어질 때", "when unpredictable situations drag on"],

  // ── axis interpretation (Part 03) ──
  ["적응성/유연성", "adaptability/flexibility"],
  ["성장지향성", "growth orientation"],
  ["안정지향성", "stability orientation"],
  ["체계성", "structure orientation"],
  ["자율성", "autonomy orientation"],
  ["관계지향성", "connection orientation"],
  ["본래 더 편한 방식", "The way that comes more naturally"],
  ["원래 나는 어떤 방식이 자연스러운가?", "Which way is naturally mine?"],
  ["현실에서 익숙해진 방식", "The way real life made familiar"],
  ["실제 삶에서는 어떤 방식을 더 많이 사용하게 되었는가?", "Which way do I actually use more in real life?"],
  ["그 과정에서 얻은 힘", "The strength gained along the way"],
  ["그렇게 살아오면서 나는 무엇을 더 잘하게 되었는가?", "What did I get better at by living this way?"],
  ["살아오며 생긴 힘", "Strength built over time"],
  ["불확실한 상황에서도 직접 기준과 순서를 만들고, 복잡한 일을 체계적으로 정리하는 능력이 발달했어요", "You've built the ability to set your own standards and order even in uncertain situations, and to organize complicated things systematically"],
  ["구조적인 환경은 편안함을 줍니다", "structured environments feel comfortable"],
  ["대신 더 많이 쓰게 된 에너지", "The energy it costs"],
  ["이렇게 적응한 방식을 계속 사용할 때, 나는 무엇 때문에 지치는가?", "When I keep using this adapted way, what wears me out?"],
  ["그만큼 드는 에너지", "The energy it takes"],
  ["모든 것이 충분히 정리되어야 움직일 수 있다고 느끼는 순간에는, 계획을 세우고 확인하는 데 생각보다 많은 에너지를 쓰게 돼요", "When you feel you can only move once everything is thoroughly sorted, you end up spending more energy than you'd expect on planning and checking"],
  ["규칙이 자주 바뀌면 에너지가 소모될 수 있어요", "energy can drain when rules change often"],
  ["변화가 많으면 스트레스를 받습니다", "lots of change stresses you out"],
  ["변화가 많으면 스트레스를 받을 수 있어요", "lots of change can be stressful"],
  ["안정적인 환경에서는 집중할 수 있어요", "you can focus in a stable environment"],
  ["자신의 의견을 표현하면 도움이 돼요", "it helps to express your opinion"],
  ["나는 원래", "I'm naturally comfortable with"],
  ["가 자연스럽다", ""],
  ["하지만 현실에서는", "but in real life I use"],
  ["를 더 많이 사용하게 되었다", "more"],
  ["그래서", "so"],
  ["라는 능력이 발달했다", "is a capability that developed"],
  ["다만 그 방식을 계속 유지할 때", "but keeping that up"],
  ["라는 에너지가 든다.", "takes this much energy."],
  ["지금도 자연스럽게 쓰는 방식", "The way you still use naturally today"],
  ["그래서 힘을 덜 들이고 잘 쓰는 부분", "What you do well with less effort"],
  ["누가 나를 이해해서 설명해주는 것", "someone who understands me explaining me"],
  ["전문가가 제3자를 평가한 임상 기록", "a clinical record of an expert assessing a third party"],
  ["심리적 중압감을 지속적으로 받게 됩니다", "you continuously experience psychological strain"],
  ["높은 방어력을 갖추게 되었습니다", "you have developed a high level of defensiveness"],
  ["높은 중압감과 긴장감을 호소할 수 있습니다", "you may report high pressure and tension"],
  ["각종 변수로부터 차단합니다", "it shuts out all kinds of variables"],
  ["효율성을 극대화합니다", "it maximizes efficiency"],
  ["정체감을 겪습니다", "you experience a sense of stagnation"],
  ["과도한 신체적·정신적 긴장감을 유지합니다", "you maintain excessive physical and mental tension"],
  ["결정마다 마음의 무게를 크게 느끼곤 합니다", "you often feel the weight of each decision heavily"],
  ["내 중심과 영역을 단단히 지키는 힘이 생겼습니다", "you've built the strength to firmly hold your center and your territory"],
  ["몸과 마음에 긴장을 자주 쥐고 있게 됩니다", "you often end up holding tension in body and mind"],
  ["편관이 있어서", "because you have the Seven Killings ten god"],
  ["도화살이 있어서", "because you have the Peach Blossom star"],
  ["현침살이라", "you're the needle-point star type"],
  ["천을귀인이 있어", "you have the Noble Helper star"],
  ["충이 있어", "there is a clash in the chart"],
  ["형살이다", "it is a punishment star"],
  ["충이 있어서", "because there is a clash in the chart"],
  ["현침살 때문에", "because of the needle-point star"],
  ["당신은 평생...", "You've always..."],
  ["어린 시절부터...", "Since childhood..."],
  ["이 패턴이 인생 전체를...", "This pattern has shaped your whole life..."],
  ["본래의 경향 / 자연스러운 성향 / 현실에서 익숙해진 방식 / 적응해온 방식", "natural tendency / natural inclination / the way real life made familiar / the way you've adapted"],

  // ── energy (Part 05) ──
  ["잘하는 일이기 때문에 더 오래 쓰고, 더 오래 쓰기 때문에 오히려 늦게 피로를 알아차릴 수 있다", "because you're good at it you use it longer, and because you use it longer you may notice the fatigue late"],
  ["타인의 의견/확신을 지나치게 확인", "over-checking others' opinions/certainty"],
  ["여러 사람의 기대를 맞춰야 함", "having to meet several people's expectations"],
  ["상대 반응 스캐닝", "scanning the other person's reaction"],
  ["관계에서의 불안감", "anxiety in relationships"],
  ["변화에 대한 저항감", "resistance to change"],
  ["잘하고 있는데, 왜 피곤할 때가 있을까요", "You're doing well, so why do you sometimes feel tired?"],
  ["친구와의 깊은 대화", "a deep talk with a friend"],
  ["자연 속에서의 시간", "time in nature"],
  ["충분한 휴식", "plenty of rest"],
  ["충분히 쉬세요", "get plenty of rest"],
  ["명상하세요", "try meditation"],
  ["명상", "meditation"],
  ["운동", "exercise"],
  ["다른 사람의 의견을 지나치게 확인", "over-checking other people's opinions"],
  ["판단 변수를 끝까지 보류하는 신중함", "the caution of holding judgment variables open until the very end"],
  ["책임 범위가 모호한 상황에서 변수를 닫지 못해 판단이 길어지는 비용", "the cost of judgment dragging on because variables can't be closed when responsibility is unclear"],
  ["완결된 체계를 고수하는 원칙", "the principle of holding to a finished system"],
  ["기준이 수시로 바뀌는 환경에서 계획을 처음부터 다시 세워야 하는 부하", "the load of rebuilding plans from scratch in an environment where standards keep changing"],
  ["상황에 맞춰 빠르게 방식을 바꾸는 유연성", "flexibility in quickly changing your approach to fit the situation"],
  ["내 기준보다 환경 변화를 먼저 수용하여 맥락 전환 비용이 누적되는 패턴", "a pattern of accepting environmental change before your own standard, so context-switching costs pile up"],
  ["비견이 강하고", "because the Companion ten god is strong"],
  ["관성이 약해서", "because the Authority ten god is weak"],
  ["조후상 화기가 부족해서", "because Fire is lacking in seasonal balance"],
  ["귀문관살 때문에", "because of the Ghost Gate star"],

  // ── Part 04 / adaptation story / closing ──
  ["여러 모습이 모두 당신이에요", "all of these sides are you"],
  ["서로 다른 모습이 아니라 연결되어 있어요", "they aren't separate sides; they're connected"],
  ["이것도 당신의 한 부분이에요", "this is a part of you too"],
  ["현재와 본래가 조화를 이룹니다", "your present and your natural self come into harmony"],
  ["지금의 모습과 본래의 경향은 서로 다른 것이 아니라...", "Who you are now and your natural tendency aren't opposites..."],
  ["사람을 중요하게 여기는 마음과 내 공간을 지키려는 태도는 서로 반대가 아니라, 관계 안에서 흔들리지 않기 위해 함께 커진 두 힘일 수 있어요", "Caring about people and protecting your own space may not be opposites; they may be two forces that grew together so you can stay steady inside relationships"],
  ["고객님/귀하/회원님", "dear customer/valued member/esteemed guest"],
  ["~연습을 통해 ~을 높일 수 있어요", "with practice you can raise …"],
  ["~하다면 더 많은 기회를 잡을 수 있어요", "if you …, you can seize more opportunities"],
  ["더 나은 균형을 찾아가는 것이 중요해요", "it's important to keep finding a better balance"],
  ["균형을 찾는 과정에서 ~ 회복할 수 있을 거예요", "in the process of finding balance you'll be able to recover …"],
  ["앞으로도 계속 성장해 나갈 수 있을 거예요", "you'll keep growing from here"],
  ["~하는 것이 중요하다는 점을 인식/기억해야 해요", "you need to recognize/remember that it's important to …"],
  ["~은 당신의 삶을 더 풍요롭게 만들어줄 거예요", "… will make your life richer"],
  ["~연습해보세요", "try practicing …"],
  ["~연습해 보세요", "try practicing …"],
  ["~활용해보세요", "try using …"],
  ["~활용해 보세요", "try using …"],
  ["~시도해보세요", "try …"],
  ["~시도해 보세요", "try …"],
  ["~기억하세요", "remember to …"],
  ["~할 필요가 생길 수 있어요", "you may need to …"],
  ["~해야 해요", "you have to …"],
  ["~할 필요가 있어요", "you need to …"],
  ["~하는 것이 중요해요", "it's important to …"],
  ["해보세요", "give it a try"],
  ["이런 균형을 찾는 과정에서 [자질]도 다시 회복할 수 있을 거예요", "In finding this balance, you'll be able to recover [quality] too"],
  ["행동]하면 삶이 더 풍요로워질 거예요", "behavior], your life will get richer"],
  ["~게 되었다는 점입니다.", "…, and that is what you can now see."],
  ["~게 되었습니다.", "…, and that is how it came to be."],
  ["조용한 매듭", "Quiet Knot"],

  // ── Part B: relationships / environment / future ──
  ["잘 맞는 사람들", "People who fit me"],
  ["내 결론을 대신 정해주기보다 독립적 판단 공간과 시간을 주는 사람", "someone who gives me space and time to judge independently instead of deciding my conclusion for me"],
  ["조율 압박 없이 내 내면의 기준을 차분하게 정리할 수 있음", "I can calmly sort out my own inner standard without pressure to negotiate"],
  ["좋은 사람", "a good person"],
  ["이해심 많은 사람", "an understanding person"],
  ["소통 잘하는 사람", "a good communicator"],
  ["신뢰할 수 있는 사람", "a trustworthy person"],
  ["공감을 잘하는 사람이 잘 맞는다", "people who are good at empathy fit well"],
  ["마찰이 생기는 지점", "Where friction shows up"],
  ["무책임한 방식", "an irresponsible way of acting"],
  ["가식적인 태도", "a fake attitude"],
  ["이기적인 사람", "a selfish person"],
  ["우유부단한 사람", "an indecisive person"],
  ["감정적인 사람", "an emotional person"],
  ["소통을 못하는 사람", "a poor communicator"],
  ["정보가 사전에 공유되지 않아 다음 수순을 예측하기 어려워지는 소통", "communication where information isn't shared ahead of time, so it's hard to predict the next step"],
  ["말과 행동의 차이가 커서 상대의 진짜 의도를 계속 해석해야 하는 관계", "a relationship where words and actions differ so much that you keep having to decode the other person's real intent"],
  ["이렇게 말하면 더 잘 들려요", "Say it this way and it lands better"],
  ["나를 닫게 만드는 방식", "What shuts me down"],
  ["왜 또 네 방식대로만 다 정하려고 해?", "Why do you always have to decide everything your way?"],
  ["그냥 시키는 대로 원래 수순 맞춰서 해", "Just do it the way you're told, follow the original steps."],
  ["내가 원하는 방향으로 일이 안 될 때...", "When things don't go the way I want..."],
  ["상황이 자주 바뀌어 혼란스러움", "feeling confused because the situation keeps changing"],
  ["내 감정이 무시당하는 느낌", "feeling that my emotions are being ignored"],
  ["라는 말을 들으면 힘들어요", "…it's hard for me when I hear that"],
  ["나에게 더 잘 들어오는 방식", "What reaches me better"],
  ["이 건은 같이 합의해야 해. 네가 먼저 생각한 범위를 말해주면 내가 필요한 부분만 이야기할게", "We need to agree on this one together. Tell me the scope you've already thought through, and I'll only raise what I need to."],
  ["어떤 배움을 얻을 수 있을지 기대돼", "I'm looking forward to what we might learn"],
  ["네 유연한 접근법이 좋아", "I like your flexible approach"],
  ["다양한 가능성을 이야기해보자", "Let's talk through the different possibilities"],
  ["네 생각을 존중해", "I respect your thinking"],
  ["성장을 응원해", "I'm cheering on your growth"],
  ["라고 물어보는 것이 더 안정적이에요", "…asking it that way feels more stable"],
  ["라고 제안하는 것이 좋겠어요", "…it would be better to suggest it that way"],
  ["나에게 잘 맞는 환경", "Environments that fit me"],
  ["역할과 목표는 분명하지만 맡은 영역의 판단과 실행에는 자율권이 보장되는 환경", "an environment where roles and goals are clear, but you keep autonomy over judgment and execution in your own area"],
  ["우선순위와 기준이 명확하고 변경 시 이유와 다음 수순이 미리 공유되는 환경", "an environment where priorities and standards are clear, and the reason and next steps are shared ahead of any change"],
  ["새로운 문제와 아이디어를 계속 접할 수 있지만 모든 우선순위가 동시에 엎어지지는 않는 협업 문화", "a collaborative culture where you keep meeting new problems and ideas without every priority being overturned at once"],
  ["의사결정 주도권과 책임 범위가 명확하여 판단 지연이나 핑퐁 없이 효율적으로 마무리되는 환경", "an environment where decision ownership and scope of responsibility are clear, so things wrap up efficiently without stalled judgment or back-and-forth"],
  ["절차와 수순이 잘 정리되어 있어 판을 매번 다시 해석하지 않아도 되는 안정된 시스템", "a stable system where procedures and steps are well laid out, so you don't have to reinterpret the situation each time"],
  ["지루한 루틴에 갇히지 않고 새로운 시도와 자극이 지속되는 환경", "an environment where you aren't stuck in dull routine and new attempts and stimulation keep coming"],
  ["조용한 환경", "a quiet environment"],
  ["자유로운 환경", "a free environment"],
  ["안정적인 환경", "a stable environment"],
  ["혼자 있을 수 있는 시간", "time alone"],
  ["명확한 규칙이 있는 상황", "situations with clear rules"],
  ["당신에게 다가올 것", "what's coming your way"],
  ["앞으로 이런 일이 생길 거예요", "this kind of thing will happen to you"],
  ["당신의 미래에는", "in your future"],
  ["다음 단계에서는 반드시", "in the next stage you must"],
  ["성장할 것입니다", "you will grow"],
  ["미래에는 ~할 것입니다", "in the future you will …"],
  ["성공할 것입니다", "you will succeed"],
  ["고객님", "dear customer"],
  ["회원님", "valued member"],
  ["귀하", "esteemed guest"],
  ["응원합니다", "we're rooting for you"],
  ["더 나은 사람이", "a better person"],
  ["성장해야", "you must grow"],
  ["노력하세요", "make an effort"],
  ["작은 성공을 축하하세요", "celebrate small wins"],
  ["반드시", "absolutely"],
  ["무엇을 굳이 바꾸지 않아도 되는가?", "What doesn't need to change?"],
  ["계속 가져갈 것", "What to keep carrying"],
  ["조금 덜 해도 되는 것", "What you can do a bit less of"],
  ["무엇을 계속 증명하거나 수행하지 않아도 되는가?", "What do you no longer have to keep proving or performing?"],
  ["다시 회복해도 되는 것", "What you can take back"],
  ["내가 다시 내 쪽으로 가져와도 되는 것은 무엇인가?", "What can I bring back to my side?"],
  ["중요한 선택에서 다른 사람의 관점을 충분히 들은 뒤에도, 마지막 판단은 자신의 내면 신호로 돌아와도 괜찮다는 점을 기억하세요", "Even after fully hearing other people's views on an important choice, it's fine for the final judgment to come back to your own inner signal"],
  ["선택할 때 기억할 단 하나의 기준", "The one criterion to remember when choosing"],
  ["앞으로 중요한 선택을 앞두고", "When you face an important choice ahead"],
  ["한 환경을 우선 선택하고", "environment first, and"],
  ["한 상황은 되도록 피하는 것을 하나의 판단 기준으로 삼을 수 있어요", "situations whenever you can, as your one decision criterion"],
  ["지금 당신에게 가장 중요한 한 가지", "The one thing that matters most for you right now"],
  ["다음 중요한 결정을 앞두고 다른 사람의 의견을 묻기 전에, 먼저 '나는 지금 무엇을 원하지?'를 한 문장으로 적어보세요", "Before your next important decision, before asking anyone else's opinion, write one sentence: 'What do I want right now?'"],
  ["자신감을 키우세요", "build your confidence"],
  ["기록하세요", "keep a record"],
  ["친구에게 연락하세요", "reach out to a friend"],
  ["이번 주 하루를 골라 기억에 남는 순간 하나를 적어보세요", "pick one day this week and write down one memorable moment"],
  ["도화살, 현침살, 천을귀인, 십신, 격국, 용신 등 사주 용어 일체 사용 금지", "no traditional Saju terms of any kind may be used"],
  ["반드시 행동적 소통/선택 수순 표현으로만 녹일 것", "translate them only into behavioral communication/decision-step language"],
  ["성장/변화/배움/시도/방향/경험", "growth/change/learning/trying/direction/experience"],
  ["수순/구조/계획/체계", "steps/structure/plan/system"],
  ["판단/결정/기준/주체성", "judgment/decision/standard/agency"],
  ["차이를 인식하게 되었다는 점입니다", "that you've come to recognize the difference"],
  ["차이를 이해하게 되었다는 점입니다", "that you've come to understand the difference"],
  ["더욱 자신감 있게", "more confidently"],
  ["성장할 수 있어요", "you can grow"],
  ["도움이 될 거예요", "it will help"],
  ["오늘 / 이번 주 / 한 번 / 한 상황 / 일정에 한 칸 / 한 문장 적기", "today / this week / once / one situation / one slot on the calendar / write one sentence"],
  ["적는다 / 정리한다 / 한 번 시도한다 / 일정에 넣는다", "write down / sort out / try once / put on the calendar"],
  ["~해보세요 / ~하는 것이 좋아요 / ~하는 것이 중요해요", "'try to…' / 'it's good to…' / 'it's important to…'"],
  ["이번 주 감정이 격해질 때 깊게 숨을 쉬어보세요", "This week, when emotions run high, try taking a deep breath"],
  ["감정이 격해질 때 깊게 숨을 쉬고 감정을 정리하세요", "When emotions run high, breathe deeply and sort out your feelings"],
  ["이번 주 갈등이 있었던 한 상황을 골라, 그때 바로 말하지 못했던 내용을 한 문장으로 적어보세요", "Pick one situation this week where there was conflict, and write in one sentence what you couldn't say right then"],
  ["이번 주", "this week"],
  ["귀문, 현침", "ghost gate, needle point"],
  ["In Korean specifically, the item should contain", "In English, the item should contain"],
];

const ORDERED = [...EN_EXAMPLES].sort((a, b) => b[0].length - a[0].length);

/** Replace Korean sample sentences with English equivalents (en-US prompts only). */
export function localizePromptExamplesEn(prompt: string): string {
  let out = prompt;
  for (const [ko, en] of ORDERED) {
    if (out.includes(ko)) out = out.split(ko).join(en);
  }
  return out;
}
