/**
 * 34 Canonical Relationship Lenses Capability & Evidence Specification
 *
 * Phase 1 Architecture: Rigorous specification of required evidence, Personal CE meanings,
 * Pair CE meanings, directionality, abstention rules, confidence rules, and classifications
 * across Partner (10), Family (8), Friend (8), and Work (8) domains.
 */

import type { DomainLensId, PartnerLensId, FamilyLensId, FriendLensId, WorkLensId } from "./types";

export type LensSupportClassification =
  | "SUPPORTABLE_NOW"
  | "SUPPORTABLE_AFTER_PERSONAL_CE_ENHANCEMENT"
  | "SUPPORTABLE_AFTER_PAIR_CE_ENHANCEMENT"
  | "REQUIRES_BOTH_CE_ENHANCEMENTS"
  | "NOT_SAFELY_SUPPORTABLE_FROM_CURRENT_SAJU_DATA";

export type LensCapabilitySpec = {
  lens_id: DomainLensId;
  domain: "partner" | "family" | "friend" | "work";
  user_question_ko: string;
  user_question_en: string;
  required_personal_ce_a: string[];
  required_personal_ce_b: string[];
  required_pair_ce_meanings: string[];
  supporting_raw_saju_facts: string[];
  directional_status: "directional" | "symmetric" | "dual_polarity";
  minimum_evidence_threshold: string;
  corroborating_evidence: string[];
  contradiction_handling: string;
  unknown_hour_dependency: "none" | "low_impact" | "high_impact";
  abstention_rule: string;
  confidence_rule: string;
  canonical_meaning_variants: {
    variant_id: string;
    description_ko: string;
    evidence_trigger: string;
  }[];
  planner_chapter_destination: "chapter_core_resonance" | "chapter_daily_coordination" | "chapter_friction_repair";
  relevant_ten_god_expressions: string[];
  support_classification: LensSupportClassification;
};

export const LENS_CAPABILITY_SPECIFICATIONS: Record<
  PartnerLensId | FamilyLensId | FriendLensId | WorkLensId,
  LensCapabilitySpec
> = {
  // ==========================================================================
  // PARTNER DOMAIN (10 LENSES)
  // ==========================================================================
  partner_core_bond: {
    lens_id: "partner_core_bond",
    domain: "partner",
    user_question_ko: "두 사람이 함께할 때 형성되는 근본적인 애착과 가치관의 결속력은?",
    user_question_en: "What fundamental attachment and value resonance form when the two unite?",
    required_personal_ce_a: ["identity_core", "day_master_strength"],
    required_personal_ce_b: ["identity_core", "day_master_strength"],
    required_pair_ce_meanings: ["stable_bonding_resources", "directional_support_exchange"],
    supporting_raw_saju_facts: ["cross_hits.stem_combine", "cross_hits.branch_six_combine", "element_flow"],
    directional_status: "dual_polarity",
    minimum_evidence_threshold: "At least 1 stem combine, branch combine, or non-conflicting element flow",
    corroborating_evidence: ["johu_relation.temperature_complement", "trio_hits.branch_three_combine"],
    contradiction_handling: "Combine with simultaneous clash generates 'dynamic magnetic bond' with elevated tension",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if no combine, no element flow, and both charts have empty cross-hits",
    confidence_rule: "high if day-day combine + element flow; medium if year/month combine or unknown hour; insufficient if no hits",
    canonical_meaning_variants: [
      { variant_id: "partner_bond_stem_resonance", description_ko: "천간합 기반의 본질적 가치관 일치와 깊은 정신적 유대", evidence_trigger: "Day/Month stem combine hit" },
      { variant_id: "partner_bond_complementary_values", description_ko: "오행 보완에 기반한 상호성장형 결속", evidence_trigger: "Element flow without stem combine" },
      { variant_id: "partner_bond_dynamic_magnetic", description_ko: "강한 매력과 긴장이 공존하는 역동적 결속", evidence_trigger: "Combine + clash simultaneous hits" },
      { variant_id: "partner_bond_insufficient_evidence", description_ko: "핵심 결속에 대한 사주 근거 부족 (중립 평가)", evidence_trigger: "No cross hits or element flow" },
    ],
    planner_chapter_destination: "chapter_core_resonance",
    relevant_ten_god_expressions: ["비견/겁재 (동반자적 연대)", "정인/편인 (정서적 지지)"],
    support_classification: "SUPPORTABLE_NOW",
  },

  partner_operating_cfo: {
    lens_id: "partner_operating_cfo",
    domain: "partner",
    user_question_ko: "가계 재정과 자산 관리, 지출 통제에서 누가 더 실질적 주도권을 쥐어야 할까?",
    user_question_en: "Who should take practical stewardship over household finances and budget control?",
    required_personal_ce_a: ["resource_governance_style", "wealth_god_rootedness"],
    required_personal_ce_b: ["resource_governance_style", "wealth_god_rootedness"],
    required_pair_ce_meanings: ["resource_responsibility_exchange", "directional_support_exchange"],
    supporting_raw_saju_facts: ["ten_god_counts.정재", "ten_god_counts.편재", "element_flow.direction"],
    directional_status: "directional",
    minimum_evidence_threshold: "Personal wealth/officer distribution or clear element flow direction",
    corroborating_evidence: ["Day branch wealth star", "Month pillar official star"],
    contradiction_handling: "Both strong wealth stars -> strategic split (investing vs budget defense)",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if neither party has wealth/officer profile and element flow is null",
    confidence_rule: "high if wealth star rootedness confirmed; medium if derived from element flow only",
    canonical_meaning_variants: [
      { variant_id: "partner_cfo_party_a_lead", description_ko: "A의 꼼꼼한 관리력과 예산 집행 주도", evidence_trigger: "A wealth rootedness > B" },
      { variant_id: "partner_cfo_party_b_lead", description_ko: "B의 안정적 자산 배분과 가계 총괄", evidence_trigger: "B wealth rootedness > A" },
      { variant_id: "partner_cfo_dual_governance", description_ko: "수입 관리와 지출 통제의 역할 분담", evidence_trigger: "Both possess wealth/officer support" },
      { variant_id: "partner_cfo_insufficient_evidence", description_ko: "재정 주도권에 대한 사주 근거 부족", evidence_trigger: "Neither possesses wealth/officer facts" },
    ],
    planner_chapter_destination: "chapter_daily_coordination",
    relevant_ten_god_expressions: ["정재 (정밀 예산/자산 관리)", "편재 (투자/유동성 운영)"],
    support_classification: "REQUIRES_BOTH_CE_ENHANCEMENTS",
  },

  partner_household_chores: {
    lens_id: "partner_household_chores",
    domain: "partner",
    user_question_ko: "일상 가사와 생활 루틴에서 불필요한 마찰 없이 깔끔하게 분담하는 법은?",
    user_question_en: "How to smoothly allocate domestic routines and household chores without friction?",
    required_personal_ce_a: ["structure_spontaneity_preference", "decision_pace"],
    required_personal_ce_b: ["structure_spontaneity_preference", "decision_pace"],
    required_pair_ce_meanings: ["role_formation", "recurring_friction_pattern"],
    supporting_raw_saju_facts: ["cross_hits.branch_clash", "cross_hits.branch_six_combine"],
    directional_status: "symmetric",
    minimum_evidence_threshold: "Day branch interaction or personal structure preference",
    corroborating_evidence: ["Johu moisture gap", "Month branch interaction"],
    contradiction_handling: "Branch clash -> explicit zone division rather than shared spontaneous tasks",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no branch relation and no personal structure data",
    confidence_rule: "high if day branch clash/combine; medium if month branch only",
    canonical_meaning_variants: [
      { variant_id: "partner_chores_zone_division", description_ko: "구역별 책임제 분담으로 마찰 방지", evidence_trigger: "Day branch clash / friction hit" },
      { variant_id: "partner_chores_fluid_synergy", description_ko: "손발이 자연스럽게 맞는 유연한 협력", evidence_trigger: "Day branch combine / bonding hit" },
      { variant_id: "partner_chores_insufficient_evidence", description_ko: "가사 분담 지표 부족 (중립 협의)", evidence_trigger: "No branch interactions" },
    ],
    planner_chapter_destination: "chapter_daily_coordination",
    relevant_ten_god_expressions: ["정관 (생활 원칙 준수)", "식신 (자연스러운 돌봄/가사)"],
    support_classification: "SUPPORTABLE_AFTER_PAIR_CE_ENHANCEMENT",
  },

  partner_private_sanctuary: {
    lens_id: "partner_private_sanctuary",
    domain: "partner",
    user_question_ko: "한 지붕 아래에서 서로의 온전한 쉼과 독립적 공간을 지켜주는 방법은?",
    user_question_en: "How to preserve individual solitude and personal sanctuaries under one roof?",
    required_personal_ce_a: ["solitude_autonomy_need", "energy_pattern"],
    required_personal_ce_b: ["solitude_autonomy_need", "energy_pattern"],
    required_pair_ce_meanings: ["closeness_versus_space_mismatch", "intimacy_boundary_dynamic"],
    supporting_raw_saju_facts: ["cross_hits.wonjin_guimun", "cross_hits.gongmang"],
    directional_status: "symmetric",
    minimum_evidence_threshold: "Wonjin/Guimun hit or strong personal solitude indicator",
    corroborating_evidence: ["Day branch isolation", "Cold johu score"],
    contradiction_handling: "Strong bond + wonjin -> deep devotion with periodic solitude requirement",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if no wonjin/gongmang and neutral solitude needs",
    confidence_rule: "high if day wonjin; medium if year/month wonjin or gongmang",
    canonical_meaning_variants: [
      { variant_id: "partner_space_solitude_cave_required", description_ko: "각자의 충전 동굴과 비침범 시간 보장", evidence_trigger: "Day wonjin/guimun hit" },
      { variant_id: "partner_space_natural_coexistence", description_ko: "자연스러운 공존과 편안한 근접성", evidence_trigger: "No wonjin/tension hits" },
      { variant_id: "partner_space_insufficient_evidence", description_ko: "독립 공간 지표 부족", evidence_trigger: "No relevant hits" },
    ],
    planner_chapter_destination: "chapter_core_resonance",
    relevant_ten_god_expressions: ["편인 (깊은 내면/사색 공간)", "비견 (독립적 자아 영역)"],
    support_classification: "SUPPORTABLE_AFTER_PAIR_CE_ENHANCEMENT",
  },

  partner_bedroom_intimacy: {
    lens_id: "partner_bedroom_intimacy",
    domain: "partner",
    user_question_ko: "스킨십과 침실의 체감 온도, 수면 리듬을 조화롭게 맞추는 방법은?",
    user_question_en: "How to harmonize tactile affection, bedroom intimacy, and sleep rhythms?",
    required_personal_ce_a: ["affection_signaling_style", "johu_temperature_band"],
    required_personal_ce_b: ["affection_signaling_style", "johu_temperature_band"],
    required_pair_ce_meanings: ["intimacy_boundary_dynamic", "emotional_pace_mismatch"],
    supporting_raw_saju_facts: ["johu_relation.temperature_complement", "cross_hits.branch_six_combine", "cross_hits.branch_clash"],
    directional_status: "dual_polarity",
    minimum_evidence_threshold: "Johu relation or day branch interaction",
    corroborating_evidence: ["Stem combine", "Johu moisture balance"],
    contradiction_handling: "Temperature mismatch with branch combine -> affectionate warmth requiring physical temperature compromise (e.g. separate blankets)",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if johu is neutral and no day branch relations exist",
    confidence_rule: "high if day branch combine/clash + johu confirmed; medium if johu only",
    canonical_meaning_variants: [
      { variant_id: "partner_bedroom_thermal_complement", description_ko: "조후 상호보완으로 인한 포근한 스킨십과 안정적 수면", evidence_trigger: "johu complement + branch combine" },
      { variant_id: "partner_bedroom_pace_calibration", description_ko: "수면 환경과 접촉 리듬의 섬세한 맞춤 필요", evidence_trigger: "johu mismatch or branch clash" },
      { variant_id: "partner_bedroom_insufficient_evidence", description_ko: "침실 친밀도 지표 부족", evidence_trigger: "No branch hit and neutral johu" },
    ],
    planner_chapter_destination: "chapter_daily_coordination",
    relevant_ten_god_expressions: ["식신 (자연스러운 스킨십)", "상관 (감각적 표현/매력)"],
    support_classification: "REQUIRES_BOTH_CE_ENHANCEMENTS",
  },

  partner_conflict_trigger: {
    lens_id: "partner_conflict_trigger",
    domain: "partner",
    user_question_ko: "의견 대립 시 말꼬리를 잡거나 방어적이 되지 않고 안전하게 해소하는 대화법은?",
    user_question_en: "How to de-escalate defensiveness and resolve heated disagreements safely?",
    required_personal_ce_a: ["conflict_response_style", "criticism_sensitivity"],
    required_personal_ce_b: ["conflict_response_style", "criticism_sensitivity"],
    required_pair_ce_meanings: ["conflict_activation_pattern", "repair_entry_point"],
    supporting_raw_saju_facts: ["cross_hits.stem_clash", "cross_hits.branch_clash", "cross_hits.wonjin_guimun"],
    directional_status: "dual_polarity",
    minimum_evidence_threshold: "At least 1 clash, punishment, or wonjin hit",
    corroborating_evidence: ["Stem clash + branch clash combination", "Personal guan/clash presence"],
    contradiction_handling: "Both stem and branch clashes -> distinct separation of cognitive clash vs emotional clash",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if no tension hits and both personal conflict styles are neutral",
    confidence_rule: "high if day stem/branch clash; medium if month/year clash",
    canonical_meaning_variants: [
      { variant_id: "partner_conflict_cognitive_cushion", description_ko: "표현 직설성 완화와 대화 쿠션어 도입", evidence_trigger: "Stem clash hit" },
      { variant_id: "partner_conflict_cooling_pause", description_ko: "감정 과열 시 즉각 쿨링타임 타임아웃", evidence_trigger: "Branch clash / wonjin hit" },
      { variant_id: "partner_conflict_insufficient_evidence", description_ko: "갈등 뇌관 지표 부족 (기본 평온)", evidence_trigger: "No clash/tension hits" },
    ],
    planner_chapter_destination: "chapter_friction_repair",
    relevant_ten_god_expressions: ["상관 (비판/직설 화법 주의)", "편관 (압박감/방어기제 해제)"],
    support_classification: "SUPPORTABLE_AFTER_PAIR_CE_ENHANCEMENT",
  },

  partner_tempo_rhythm: {
    lens_id: "partner_tempo_rhythm",
    domain: "partner",
    user_question_ko: "결정의 속도, 외출 준비, 휴일 라이프스타일의 템포 차이는 어떻게 맞출까?",
    user_question_en: "How to harmonize differing decision speeds, preparation tempos, and weekend rhythms?",
    required_personal_ce_a: ["decision_pace_style", "energy_pattern"],
    required_personal_ce_b: ["decision_pace_style", "energy_pattern"],
    required_pair_ce_meanings: ["emotional_pace_mismatch", "decision_coordination_flow"],
    supporting_raw_saju_facts: ["element_flow.interaction_code", "element_flow.direction"],
    directional_status: "directional",
    minimum_evidence_threshold: "Element flow direction or personal pace contrast",
    corroborating_evidence: ["Twelve stage energy contrast", "Dominant element polarity"],
    contradiction_handling: "Speed asymmetry -> buffer time agreements and lead delegation",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if element flow is neutral and personal paces are identical",
    confidence_rule: "high if element flow clear; medium if balanced",
    canonical_meaning_variants: [
      { variant_id: "partner_tempo_pace_asymmetry", description_ko: "속도 차이를 인정하고 준비 버퍼 시간 확보", evidence_trigger: "element overcomes or strong generates" },
      { variant_id: "partner_tempo_synchronized_flow", description_ko: "자연스러운 행동 리듬과 휴식의 일치", evidence_trigger: "element same or gentle flow" },
      { variant_id: "partner_tempo_insufficient_evidence", description_ko: "템포 차이 지표 부족", evidence_trigger: "No element flow data" },
    ],
    planner_chapter_destination: "chapter_daily_coordination",
    relevant_ten_god_expressions: ["식상 (빠른 발상/실행)", "인성 (심사숙고/완만함)"],
    support_classification: "SUPPORTABLE_AFTER_PERSONAL_CE_ENHANCEMENT",
  },

  partner_crisis_protector: {
    lens_id: "partner_crisis_protector",
    domain: "partner",
    user_question_ko: "질병, 실직, 재정 위기 등 인생의 풍파가 닥쳤을 때 서로를 지키는 방식은?",
    user_question_en: "How do the partners rally together and protect each other during life crises?",
    required_personal_ce_a: ["pressure_response", "support_giving_style"],
    required_personal_ce_b: ["pressure_response", "support_giving_style"],
    required_pair_ce_meanings: ["pressure_amplification_or_buffering", "stable_bonding_resources"],
    supporting_raw_saju_facts: ["cross_hits.branch_six_combine", "trio_hits", "cross_hits.stem_combine"],
    directional_status: "dual_polarity",
    minimum_evidence_threshold: "At least 1 combine or supportive element flow",
    corroborating_evidence: ["Noble star presence", "Yongsin alignment"],
    contradiction_handling: "Crisis triggers high bond if supportive combines anchor the chart",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if no supportive combines exist",
    confidence_rule: "high if branch six-combine/trio; medium if single combine",
    canonical_meaning_variants: [
      { variant_id: "partner_crisis_unbreakable_fortress", description_ko: "위기 앞에서 더욱 끈끈해지는 방어벽과 역할 결속", evidence_trigger: "Branch combine / trio hits" },
      { variant_id: "partner_crisis_resilient_support", description_ko: "담담하게 서로를 지탱하는 든든한 신뢰", evidence_trigger: "Stem combine or yongsin overlap" },
      { variant_id: "partner_crisis_insufficient_evidence", description_ko: "위기 결속 지표 부족", evidence_trigger: "No supportive hits" },
    ],
    planner_chapter_destination: "chapter_friction_repair",
    relevant_ten_god_expressions: ["정관/정인 (책임과 품어줌)", "편관 (위기 돌파력)"],
    support_classification: "SUPPORTABLE_NOW",
  },

  partner_parenting_alignment: {
    lens_id: "partner_parenting_alignment",
    domain: "partner",
    user_question_ko: "자녀 양육관, 훈육 방식, 교육 철학에서 충돌 없이 원팀으로 조율하는 법은?",
    user_question_en: "How to align parenting philosophies, discipline styles, and education values as one team?",
    required_personal_ce_a: ["recognition_need_style", "structure_spontaneity_preference"],
    required_personal_ce_b: ["recognition_need_style", "structure_spontaneity_preference"],
    required_pair_ce_meanings: ["role_formation", "decision_coordination_flow"],
    supporting_raw_saju_facts: ["cross_hits.stem_clash", "cross_hits.branch_six_combine"],
    directional_status: "dual_polarity",
    minimum_evidence_threshold: "Personal officer/food god profile or cross-hit evidence",
    corroborating_evidence: ["Hour pillar facts (if available)", "Day/Month structure"],
    contradiction_handling: "Warmth vs discipline polarity -> assign explicit good-cop/guidance-cop roles",
    unknown_hour_dependency: "high_impact",
    abstention_rule: "Abstain if birth times unknown and no cross-chart indicators",
    confidence_rule: "medium if hour unknown; high if hour known and cross-hits confirmed",
    canonical_meaning_variants: [
      { variant_id: "partner_parenting_complementary_roles", description_ko: "훈육과 정서 지지의 균형 잡힌 역할 분담", evidence_trigger: "Combine + complementary officer/food profiles" },
      { variant_id: "partner_parenting_unified_standard", description_ko: "일관된 원칙을 공유하는 단단한 교육 철학", evidence_trigger: "Stem combine or harmonious element flow" },
      { variant_id: "partner_parenting_insufficient_evidence", description_ko: "양육 조율 지표 부족", evidence_trigger: "No relevant hits" },
    ],
    planner_chapter_destination: "chapter_daily_coordination",
    relevant_ten_god_expressions: ["식신/상관 (자녀에 대한 공감과 지지)", "정관/편관 (규칙과 훈육 기준)"],
    support_classification: "REQUIRES_BOTH_CE_ENHANCEMENTS",
  },

  partner_longterm_vision: {
    lens_id: "partner_longterm_vision",
    domain: "partner",
    user_question_ko: "노후 계획, 커리어 전환, 거주지 이동 등 10년 뒤의 큰 그림은 일치할까?",
    user_question_en: "Do the partners' 10-year life visions, retirement plans, and long-term milestones align?",
    required_personal_ce_a: ["leadership_responsibility", "resource_governance_style"],
    required_personal_ce_b: ["leadership_responsibility", "resource_governance_style"],
    required_pair_ce_meanings: ["stable_bonding_resources", "directional_support_exchange"],
    supporting_raw_saju_facts: ["trio_hits", "cross_hits.stem_combine", "yongsin_alignment"],
    directional_status: "symmetric",
    minimum_evidence_threshold: "Trio hit, stem combine, or yongsin overlap",
    corroborating_evidence: ["Year pillar harmony", "Element balance"],
    contradiction_handling: "Differing pacing -> phased roadmaps aligning individual career peaks",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if no trio, no stem combine, and no yongsin alignment",
    confidence_rule: "high if trio hit; medium if stem combine only",
    canonical_meaning_variants: [
      { variant_id: "partner_vision_shared_trio_horizon", description_ko: "삼합으로 묶이는 장기적 생애 목표와 가치관 공유", evidence_trigger: "Trio combine hit" },
      { variant_id: "partner_vision_parallel_alignment", description_ko: "서로의 성장 궤적을 지지하는 평행적 비전", evidence_trigger: "Stem combine / yongsin overlap" },
      { variant_id: "partner_vision_insufficient_evidence", description_ko: "장기 비전 결속 지표 부족", evidence_trigger: "No long-term combine hits" },
    ],
    planner_chapter_destination: "chapter_core_resonance",
    relevant_ten_god_expressions: ["정관/정재 (안정적 미래 설계)", "편재/편관 (확장과 도전 비전)"],
    support_classification: "SUPPORTABLE_NOW",
  },

  // ==========================================================================
  // FAMILY PARENT-CHILD DOMAIN (8 LENSES)
  // ==========================================================================
  family_core_dynamic: {
    lens_id: "family_core_dynamic",
    domain: "family",
    user_question_ko: "부모와 자녀 사이에 흐르는 본질적인 애착 관계와 기본 정서는?",
    user_question_en: "What is the foundational attachment dynamic and emotional bond between parent and child?",
    required_personal_ce_a: ["support_giving_style", "identity_core"],
    required_personal_ce_b: ["reassurance_recognition_needs", "identity_core"],
    required_pair_ce_meanings: ["directional_support_exchange", "stable_bonding_resources"],
    supporting_raw_saju_facts: ["cross_hits.stem_combine", "element_flow"],
    directional_status: "directional",
    minimum_evidence_threshold: "Stem combine or element flow direction",
    corroborating_evidence: ["Day-Month branch harmony", "Temperature complement"],
    contradiction_handling: "Generates vs clashes -> intense love with vocal expressing hurdles",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if empty cross-hits and null element flow",
    confidence_rule: "high if stem combine + element flow; medium if one hit only",
    canonical_meaning_variants: [
      { variant_id: "family_core_warm_nurture", description_ko: "따뜻한 정서적 유대와 깊은 신뢰 기반의 안전기지", evidence_trigger: "Stem combine or generates a_to_b" },
      { variant_id: "family_core_independent_bond", description_ko: "건강한 독립성을 존중하는 개별적 성장 유대", evidence_trigger: "Element flow symmetric or same" },
      { variant_id: "family_core_insufficient_evidence", description_ko: "애착 유대 지표 부족", evidence_trigger: "No hits" },
    ],
    planner_chapter_destination: "chapter_core_resonance",
    relevant_ten_god_expressions: ["인성 (무조건적 수용과 양육)", "식신 (자연스러운 보살핌)"],
    support_classification: "SUPPORTABLE_NOW",
  },

  family_discipline_friction: {
    lens_id: "family_discipline_friction",
    domain: "family",
    user_question_ko: "부모의 훈육과 기대가 자녀에게 잔소리나 압박으로 느껴질 때의 충돌은?",
    user_question_en: "How does parental guidance risk becoming perceived as pressure or nagging?",
    required_personal_ce_a: ["leadership_responsibility", "conflict_response"],
    required_personal_ce_b: ["criticism_sensitivity", "autonomy_need"],
    required_pair_ce_meanings: ["conflict_activation_pattern", "pressure_amplification_or_buffering"],
    supporting_raw_saju_facts: ["cross_hits.stem_clash", "element_flow.interaction_code"],
    directional_status: "directional",
    minimum_evidence_threshold: "Stem clash or element overcomes direction",
    corroborating_evidence: ["Branch clash", "Personal officer star excess"],
    contradiction_handling: "Cognitive clash -> use conversational cushions rather than directives",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no tension hits exist",
    confidence_rule: "high if day-day clash; medium if year/month clash",
    canonical_meaning_variants: [
      { variant_id: "family_discipline_cushion_needed", description_ko: "직설적 훈육 톤 완화와 자녀 자존감 보호 대화법", evidence_trigger: "Stem clash or overcomes hit" },
      { variant_id: "family_discipline_gentle_flow", description_ko: "성향을 거스르지 않는 자연스럽고 온화한 지도", evidence_trigger: "No clashes / supportive flow" },
      { variant_id: "family_discipline_insufficient_evidence", description_ko: "훈육 충돌 지표 부족", evidence_trigger: "No tension evidence" },
    ],
    planner_chapter_destination: "chapter_friction_repair",
    relevant_ten_god_expressions: ["편관 (강한 통제/압박 완화 필요)", "상관 (반발심 이해)"],
    support_classification: "SUPPORTABLE_AFTER_PAIR_CE_ENHANCEMENT",
  },

  family_emotional_distance: {
    lens_id: "family_emotional_distance",
    domain: "family",
    user_question_ko: "자녀의 사춘기나 독립 시기, 적절한 정서적 거리두기 공간은?",
    user_question_en: "What is the healthy emotional distance and boundary during adolescent independence?",
    required_personal_ce_a: ["autonomy_versus_closeness_need"],
    required_personal_ce_b: ["solitude_autonomy_need"],
    required_pair_ce_meanings: ["closeness_versus_space_mismatch", "intimacy_boundary_dynamic"],
    supporting_raw_saju_facts: ["cross_hits.wonjin_guimun", "cross_hits.gongmang"],
    directional_status: "symmetric",
    minimum_evidence_threshold: "Wonjin/Guimun or gongmang hit",
    corroborating_evidence: ["Day branch isolation", "Cold johu score"],
    contradiction_handling: "Wonjin requires recognizing closed bedroom doors as healthy autonomy",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if no wonjin/gongmang",
    confidence_rule: "high if day wonjin; medium if other pillars",
    canonical_meaning_variants: [
      { variant_id: "family_distance_respect_sanctuary", description_ko: "자녀의 비밀과 사생활을 존중하며 지켜보는 거리감", evidence_trigger: "Wonjin / Guimun hit" },
      { variant_id: "family_distance_warm_proximity", description_ko: "일상을 자연스럽게 나누는 편안한 소통", evidence_trigger: "No wonjin hits" },
      { variant_id: "family_distance_insufficient_evidence", description_ko: "거리 조절 지표 부족", evidence_trigger: "No relevant hits" },
    ],
    planner_chapter_destination: "chapter_core_resonance",
    relevant_ten_god_expressions: ["편인 (내면 충전/비밀 공간 존중)", "비견 (독립적 개체 인정)"],
    support_classification: "SUPPORTABLE_NOW",
  },

  family_hidden_needs: {
    lens_id: "family_hidden_needs",
    domain: "family",
    user_question_ko: "말로 표현하지 못하는 자녀의 진짜 불안과 인정받고 싶은 욕구는?",
    user_question_en: "What are the unspoken developmental anxieties and validation longings of the child?",
    required_personal_ce_a: ["support_giving_style"],
    required_personal_ce_b: ["hidden_vulnerability", "reassurance_recognition_needs"],
    required_pair_ce_meanings: ["hidden_needs_interaction", "directional_support_exchange"],
    supporting_raw_saju_facts: ["element_flow.direction", "cross_hits.wonjin_guimun"],
    directional_status: "directional",
    minimum_evidence_threshold: "Element flow or personal vulnerability profile for B",
    corroborating_evidence: ["Weakest element in B", "Gongmang on B"],
    contradiction_handling: "Inward anxiety masked by rebellious behavior",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if no vulnerability facts and null element flow",
    confidence_rule: "high if B vulnerability profile confirmed; medium if element flow only",
    canonical_meaning_variants: [
      { variant_id: "family_needs_validation_longing", description_ko: "결과보다 과정의 노력을 알아줄 때 차오르는 안도감", evidence_trigger: "Element flow generates b or wonjin" },
      { variant_id: "family_needs_autonomy_affirmation", description_ko: "스스로 해낼 수 있다는 신뢰를 확인할 때의 자존감", evidence_trigger: "Element flow same/weak" },
      { variant_id: "family_needs_insufficient_evidence", description_ko: "숨은 욕구 지표 부족", evidence_trigger: "No relevant facts" },
    ],
    planner_chapter_destination: "chapter_core_resonance",
    relevant_ten_god_expressions: ["정인 (무조건적 인정 갈망)", "편재/편관 (인정 욕구와 평가 불안)"],
    support_classification: "REQUIRES_BOTH_CE_ENHANCEMENTS",
  },

  family_praise_trigger: {
    lens_id: "family_praise_trigger",
    domain: "family",
    user_question_ko: "자녀의 자존감을 키우고 잠재력을 폭발시키는 가장 효과적인 칭찬법은?",
    user_question_en: "What specific praise and encouragement triggers maximize the child's potential?",
    required_personal_ce_a: ["expression_signaling_style"],
    required_personal_ce_b: ["reassurance_recognition_needs", "talent_expression_channel"],
    required_pair_ce_meanings: ["mutual_recognition_pattern"],
    supporting_raw_saju_facts: ["cross_hits.branch_six_combine", "cross_hits.stem_combine"],
    directional_status: "directional",
    minimum_evidence_threshold: "Branch combine or personal recognition profile",
    corroborating_evidence: ["Food god in B", "Positive element flow"],
    contradiction_handling: "Generic praise fails; praise specific problem-solving resilience",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no combine and neutral praise profile",
    confidence_rule: "high if branch combine; medium if stem combine only",
    canonical_meaning_variants: [
      { variant_id: "family_praise_specific_process", description_ko: "구체적 문제 해결 과정과 노력을 짚어주는 맞춤형 격려", evidence_trigger: "Branch combine hit" },
      { variant_id: "family_praise_baseline", description_ko: "아이의 선택을 믿고 맡겨주는 든든한 신뢰 표현", evidence_trigger: "No combine hits" },
      { variant_id: "family_praise_insufficient_evidence", description_ko: "칭찬 반응 지표 부족", evidence_trigger: "No relevant facts" },
    ],
    planner_chapter_destination: "chapter_daily_coordination",
    relevant_ten_god_expressions: ["식신 (재능 발현 칭찬)", "정인 (정서적 안정 칭찬)"],
    support_classification: "SUPPORTABLE_AFTER_PERSONAL_CE_ENHANCEMENT",
  },

  family_household_roles: {
    lens_id: "family_household_roles",
    domain: "family",
    user_question_ko: "집안에서 각자가 맡았을 때 가장 자연스러운 역할 분담과 에너지는?",
    user_question_en: "What domestic task division and daily routines feel most natural for the family?",
    required_personal_ce_a: ["leadership_responsibility", "structure_spontaneity_preference"],
    required_personal_ce_b: ["autonomy_need", "structure_spontaneity_preference"],
    required_pair_ce_meanings: ["role_formation", "resource_responsibility_exchange"],
    supporting_raw_saju_facts: ["cross_hits.branch_clash", "cross_hits.branch_six_combine"],
    directional_status: "dual_polarity",
    minimum_evidence_threshold: "Branch interaction or personal structure data",
    corroborating_evidence: ["Day-Month relations", "Johu balance"],
    contradiction_handling: "Branch clash -> explicit age-appropriate chores rather than ad-hoc demands",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no branch interaction",
    confidence_rule: "high if day branch clash/combine; medium if month branch",
    canonical_meaning_variants: [
      { variant_id: "family_roles_collaborative_order", description_ko: "명확한 생활 구역과 역할을 나누는 협력 질서", evidence_trigger: "Branch clash / friction hit" },
      { variant_id: "family_roles_flexible_cooperation", description_ko: "유연하게 돕고 챙겨주는 조화로운 가족 역할", evidence_trigger: "Branch combine / bonding hit" },
      { variant_id: "family_roles_insufficient_evidence", description_ko: "가족 역할 분담 지표 부족", evidence_trigger: "No branch hits" },
    ],
    planner_chapter_destination: "chapter_daily_coordination",
    relevant_ten_god_expressions: ["정관 (가족 규칙과 질서)", "정재 (생활 가사 관리)"],
    support_classification: "SUPPORTABLE_AFTER_PAIR_CE_ENHANCEMENT",
  },

  family_safe_boundary: {
    lens_id: "family_safe_boundary",
    domain: "family",
    user_question_ko: "서로의 인생에 과도하게 개입하지 않고 건강한 개인을 지켜주는 경계선은?",
    user_question_en: "How to preserve healthy individuation boundaries and prevent emotional over-involvement?",
    required_personal_ce_a: ["solitude_autonomy_need", "anxiety_projection_risk"],
    required_personal_ce_b: ["solitude_autonomy_need", "individuation_drive"],
    required_pair_ce_meanings: ["closeness_versus_space_mismatch", "intimacy_boundary_dynamic"],
    supporting_raw_saju_facts: ["cross_hits.wonjin_guimun", "cross_hits.gongmang"],
    directional_status: "symmetric",
    minimum_evidence_threshold: "Wonjin/Guimun or gongmang hit",
    corroborating_evidence: ["Stem clash", "Day branch tension"],
    contradiction_handling: "Differentiate parental anxiety from child's genuine capability",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if no wonjin/gongmang hits",
    confidence_rule: "high if day wonjin; medium if other pillars",
    canonical_meaning_variants: [
      { variant_id: "family_boundary_healthy_individuation", description_ko: "부모의 기대를 앞세우기보다 자녀 고유의 길을 존중하는 경계선", evidence_trigger: "Wonjin / Guimun hit" },
      { variant_id: "family_boundary_clear_respect", description_ko: "상호 존중과 신뢰 속에서 지켜지는 편안한 경계", evidence_trigger: "No wonjin hits" },
      { variant_id: "family_boundary_insufficient_evidence", description_ko: "경계선 지표 부족", evidence_trigger: "No relevant hits" },
    ],
    planner_chapter_destination: "chapter_core_resonance",
    relevant_ten_god_expressions: ["편인 (심리적 분리 존중)", "편관 (기대치 투사 주의)"],
    support_classification: "SUPPORTABLE_NOW",
  },

  family_crisis_recovery: {
    lens_id: "family_crisis_recovery",
    domain: "family",
    user_question_ko: "가족 간 상처가 생겼을 때 빠르게 감정을 추스르고 화해하는 회복법은?",
    user_question_en: "What de-escalation routine restores emotional warmth after heated family conflicts?",
    required_personal_ce_a: ["conflict_response", "recovery_decompression_style"],
    required_personal_ce_b: ["conflict_response", "recovery_decompression_style"],
    required_pair_ce_meanings: ["repair_entry_point", "repair_loop"],
    supporting_raw_saju_facts: ["cross_hits.stem_clash", "cross_hits.branch_six_combine"],
    directional_status: "dual_polarity",
    minimum_evidence_threshold: "Stem clash or branch combine hit",
    corroborating_evidence: ["Element buffering", "Temperature complement"],
    contradiction_handling: "Cooling timeout followed by low-stakes shared food or warmth",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no tension or bonding hits",
    confidence_rule: "high if stem clash + branch combine; medium if single hit",
    canonical_meaning_variants: [
      { variant_id: "family_repair_cooling_timeout", description_ko: "감정 과열 시 즉각 훈육 중단 및 쿨링타임 화해 규칙", evidence_trigger: "Stem clash hit" },
      { variant_id: "family_repair_gentle_bridge", description_ko: "따뜻한 밥 한 끼와 다정한 눈맞춤으로 자연스럽게 풀리는 회복", evidence_trigger: "Branch combine / gentle flow" },
      { variant_id: "family_repair_insufficient_evidence", description_ko: "가족 화해 지표 부족", evidence_trigger: "No hits" },
    ],
    planner_chapter_destination: "chapter_friction_repair",
    relevant_ten_god_expressions: ["식신 (음식/활동을 통한 화해)", "정인 (품어주는 사과)"],
    support_classification: "SUPPORTABLE_AFTER_PAIR_CE_ENHANCEMENT",
  },

  // ==========================================================================
  // FRIENDSHIP DOMAIN (8 LENSES)
  // ==========================================================================
  friend_core_vibe: {
    lens_id: "friend_core_vibe",
    domain: "friend",
    user_question_ko: "함께 있을 때 가장 재미있고 편안하게 통하는 우리만의 케미스트리는?",
    user_question_en: "What playful conversational chemistry and authentic peer vibe emerge between the friends?",
    required_personal_ce_a: ["expression_signaling_style", "social_energy"],
    required_personal_ce_b: ["expression_signaling_style", "social_energy"],
    required_pair_ce_meanings: ["stable_bonding_resources", "mutual_recognition_pattern"],
    supporting_raw_saju_facts: ["cross_hits.stem_combine", "cross_hits.branch_six_combine"],
    directional_status: "symmetric",
    minimum_evidence_threshold: "Stem combine or branch combine hit",
    corroborating_evidence: ["Trio combine", "Element flow same/generates"],
    contradiction_handling: "Combine with clash -> playful teasing and banter with strong affection",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if no combine hits and empty cross-chart profile",
    confidence_rule: "high if day combine; medium if month/year combine",
    canonical_meaning_variants: [
      { variant_id: "friend_vibe_instant_click", description_ko: "코드가 찰떡같이 맞아떨어지는 티키타카 케미", evidence_trigger: "Stem combine hit" },
      { variant_id: "friend_vibe_comfortable_easygoing", description_ko: "무던하고 편안한 롱런 우정", evidence_trigger: "No combine hits / neutral flow" },
      { variant_id: "friend_vibe_insufficient_evidence", description_ko: "친구 케미 지표 부족", evidence_trigger: "No hits" },
    ],
    planner_chapter_destination: "chapter_core_resonance",
    relevant_ten_god_expressions: ["비견 (동등한 눈높이 친구)", "식신 (유쾌한 대화와 놀이)"],
    support_classification: "SUPPORTABLE_NOW",
  },

  friend_treasurer_split: {
    lens_id: "friend_treasurer_split",
    domain: "friend",
    user_question_ko: "밥값, 술값, 여행 경비 등 돈 계산할 때 서운함 없이 깔끔한 1/N 룰은?",
    user_question_en: "What transparent split-the-bill habits prevent awkwardness over dining and travel costs?",
    required_personal_ce_a: ["resource_governance_style"],
    required_personal_ce_b: ["resource_governance_style"],
    required_pair_ce_meanings: ["resource_responsibility_exchange"],
    supporting_raw_saju_facts: ["cross_hits.stem_clash", "ten_god_counts.정재", "ten_god_counts.편재"],
    directional_status: "dual_polarity",
    minimum_evidence_threshold: "Stem clash or personal wealth star distribution",
    corroborating_evidence: ["Day branch wealth star", "Element flow direction"],
    contradiction_handling: "Tension hit -> digital split app immediate settlement",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no wealth facts and no stem clash",
    confidence_rule: "high if stem clash + wealth profile; medium if clash only",
    canonical_meaning_variants: [
      { variant_id: "friend_money_exact_split_rule", description_ko: "정산 어플을 활용해 1원 단위까지 쿨하게 정리하는 원칙", evidence_trigger: "Stem clash hit" },
      { variant_id: "friend_money_easy_rotation", description_ko: "이번엔 내가 사고 다음엔 네가 사는 무던한 계산", evidence_trigger: "No clash hits" },
      { variant_id: "friend_money_insufficient_evidence", description_ko: "정산 스타일 지표 부족", evidence_trigger: "No relevant facts" },
    ],
    planner_chapter_destination: "chapter_daily_coordination",
    relevant_ten_god_expressions: ["정재 (정확한 1/N 정산)", "편재 (시원한 한턱 내기)"],
    support_classification: "SUPPORTABLE_AFTER_PERSONAL_CE_ENHANCEMENT",
  },

  friend_travel_lead: {
    lens_id: "friend_travel_lead",
    domain: "friend",
    user_question_ko: "여행을 가거나 모임을 잡을 때 계획 짜기와 일정 리드는 누가 맡아야 할까?",
    user_question_en: "Who should take the planning lead and itinerary stewardship during trips and gatherings?",
    required_personal_ce_a: ["leadership_responsibility", "structure_spontaneity_preference"],
    required_personal_ce_b: ["leadership_responsibility", "structure_spontaneity_preference"],
    required_pair_ce_meanings: ["initiative_and_response_pattern", "role_formation"],
    supporting_raw_saju_facts: ["cross_hits.branch_six_combine", "element_flow.direction"],
    directional_status: "directional",
    minimum_evidence_threshold: "Branch combine or element flow direction",
    corroborating_evidence: ["Personal officer/planner star", "Twelve stage initiative"],
    contradiction_handling: "Both planners -> divide by trip domains (accommodations vs food spots)",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no branch combine and null element flow",
    confidence_rule: "high if branch combine + element flow; medium if flow only",
    canonical_meaning_variants: [
      { variant_id: "friend_travel_itinerary_harmony", description_ko: "맛집/코스를 짜는 리더와 즐겁게 호응하는 팔로워의 조화", evidence_trigger: "Branch combine hit" },
      { variant_id: "friend_travel_spontaneous_wanderlust", description_ko: "계획 없이 떠나도 발길 닿는 대로 유쾌한 즉흥 여행", evidence_trigger: "No combine hits" },
      { variant_id: "friend_travel_insufficient_evidence", description_ko: "여행 리드 지표 부족", evidence_trigger: "No hits" },
    ],
    planner_chapter_destination: "chapter_daily_coordination",
    relevant_ten_god_expressions: ["정관/정재 (철저한 일정표 기획)", "식신/상관 (현장 즉흥 탐방)"],
    support_classification: "SUPPORTABLE_AFTER_PAIR_CE_ENHANCEMENT",
  },

  friend_emotional_vent: {
    lens_id: "friend_emotional_vent",
    domain: "friend",
    user_question_ko: "힘든 일이나 고민이 생겼을 때 서로에게 가장 든든한 하소연과 공감 방식은?",
    user_question_en: "What emotional venting and empathetic listening style best comforts each friend?",
    required_personal_ce_a: ["support_giving_style", "criticism_sensitivity"],
    required_personal_ce_b: ["reassurance_recognition_needs", "criticism_sensitivity"],
    required_pair_ce_meanings: ["mutual_recognition_pattern", "directional_support_exchange"],
    supporting_raw_saju_facts: ["cross_hits.wonjin_guimun", "element_flow"],
    directional_status: "dual_polarity",
    minimum_evidence_threshold: "Wonjin/Guimun hit or element flow direction",
    corroborating_evidence: ["Inseong presence", "Temperature complement"],
    contradiction_handling: "Wonjin -> avoid unsolicited advice; give fierce unconditional validation first",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if no wonjin and null element flow",
    confidence_rule: "high if wonjin hit; medium if element flow only",
    canonical_meaning_variants: [
      { variant_id: "friend_vent_solution_anchor", description_ko: "해결책 제시보다 오롯이 내 편이 되어주는 무조건적 공감", evidence_trigger: "Wonjin / Guimun hit" },
      { variant_id: "friend_vent_unconditional_empathy", description_ko: "담백하게 들어주고 가벼운 웃음으로 고민을 덜어주는 안식처", evidence_trigger: "No wonjin / gentle flow" },
      { variant_id: "friend_vent_insufficient_evidence", description_ko: "하소연 공감 지표 부족", evidence_trigger: "No relevant hits" },
    ],
    planner_chapter_destination: "chapter_friction_repair",
    relevant_ten_god_expressions: ["정인 (깊은 정서적 수용)", "비견 (내 일처럼 편들어주기)"],
    support_classification: "SUPPORTABLE_NOW",
  },

  friend_jealousy_guard: {
    lens_id: "friend_jealousy_guard",
    domain: "friend",
    user_question_ko: "한쪽이 먼저 성공하거나 취업/연애 등 환경이 달라졌을 때 질투를 막는 법은?",
    user_question_en: "How to celebrate mutual success genuinely and dismantle comparison envy as life paths diverge?",
    required_personal_ce_a: ["solitude_autonomy_need", "comparison_sensitivity"],
    required_personal_ce_b: ["solitude_autonomy_need", "comparison_sensitivity"],
    required_pair_ce_meanings: ["recurring_friction_pattern", "misunderstanding_translation"],
    supporting_raw_saju_facts: ["cross_hits.branch_clash", "cross_hits.branch_harm"],
    directional_status: "symmetric",
    minimum_evidence_threshold: "Branch clash or punishment/harm hit",
    corroborating_evidence: ["Peer competition god (겁재)", "Day branch tension"],
    contradiction_handling: "Recognize differing life blooming seasons to eliminate social comparison",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no branch tension hits",
    confidence_rule: "high if day branch clash; medium if month/year branch",
    canonical_meaning_variants: [
      { variant_id: "friend_jealousy_secure_boundary", description_ko: "비교 의식을 내려놓고 각자의 속도를 인정하며 축하하는 성숙함", evidence_trigger: "Branch clash / harm hit" },
      { variant_id: "friend_jealousy_natural_celebration", description_ko: "상대의 성공이 곧 나의 기쁨이 되는 건강한 축하", evidence_trigger: "No clash hits" },
      { variant_id: "friend_jealousy_insufficient_evidence", description_ko: "시기 질투 지표 부족", evidence_trigger: "No tension evidence" },
    ],
    planner_chapter_destination: "chapter_core_resonance",
    relevant_ten_god_expressions: ["비견 (건전한 동료애)", "겁재 (경쟁심 완화와 성숙한 인정)"],
    support_classification: "SUPPORTABLE_AFTER_PAIR_CE_ENHANCEMENT",
  },

  friend_comfort_distance: {
    lens_id: "friend_comfort_distance",
    domain: "friend",
    user_question_ko: "매일 연락하지 않아도 서운함 없이 언제든 편하게 만날 수 있는 적정 거리는?",
    user_question_en: "What low-maintenance contact cadence preserves deep peer friendship without pressure?",
    required_personal_ce_a: ["social_energy", "solitude_autonomy_need"],
    required_personal_ce_b: ["social_energy", "solitude_autonomy_need"],
    required_pair_ce_meanings: ["closeness_versus_space_mismatch"],
    supporting_raw_saju_facts: ["element_flow.direction", "cross_hits.wonjin_guimun"],
    directional_status: "symmetric",
    minimum_evidence_threshold: "Element flow or personal social battery profiles",
    corroborating_evidence: ["Johu coldness", "Gongmang void"],
    contradiction_handling: "Delayed replies normalized as healthy busy adult lives",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if element flow null and personal profiles neutral",
    confidence_rule: "high if personal social profiles corroborated; medium if element flow only",
    canonical_meaning_variants: [
      { variant_id: "friend_distance_low_maintenance_deep", description_ko: "연락 빈도에 연연하지 않고 오랜만에 봐도 어제 본 것 같은 담백한 거리", evidence_trigger: "Element flow present or wonjin" },
      { variant_id: "friend_distance_active_sync", description_ko: "자주 만나고 일상을 밀착 공유하는 활발한 교류", evidence_trigger: "Combine hits + warm johu" },
      { variant_id: "friend_distance_insufficient_evidence", description_ko: "연락 거리 지표 부족", evidence_trigger: "No relevant facts" },
    ],
    planner_chapter_destination: "chapter_core_resonance",
    relevant_ten_god_expressions: ["편인 (담백한 거리 유지)", "식신 (부담 없는 일상 공유)"],
    support_classification: "SUPPORTABLE_AFTER_PERSONAL_CE_ENHANCEMENT",
  },

  friend_taste_shared: {
    lens_id: "friend_taste_shared",
    domain: "friend",
    user_question_ko: "음식, 패션, 음악, 취미 등 둘이 함께 즐길 때 시너지가 폭발하는 관심사는?",
    user_question_en: "What shared hobbies, cultural tastes, and dining explorations create explosive synergy?",
    required_personal_ce_a: ["expression_signaling_style", "talent_expression_channel"],
    required_personal_ce_b: ["expression_signaling_style", "talent_expression_channel"],
    required_pair_ce_meanings: ["stable_bonding_resources"],
    supporting_raw_saju_facts: ["cross_hits.branch_six_combine", "trio_hits"],
    directional_status: "symmetric",
    minimum_evidence_threshold: "Branch combine or trio hit",
    corroborating_evidence: ["Food god in both charts", "Stem combine"],
    contradiction_handling: "Different tastes -> exciting curation of novel recommendations",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no branch combine hits",
    confidence_rule: "high if branch combine/trio; medium if stem combine only",
    canonical_meaning_variants: [
      { variant_id: "friend_taste_synergistic_discovery", description_ko: "서로의 취향을 공유하며 새로운 경험을 넓혀가는 시너지", evidence_trigger: "Branch combine / trio hit" },
      { variant_id: "friend_taste_complementary_fun", description_ko: "서로 다른 관심사를 구경하며 색다른 재미를 얻는 조화", evidence_trigger: "No combine hits" },
      { variant_id: "friend_taste_insufficient_evidence", description_ko: "취향 공유 지표 부족", evidence_trigger: "No hits" },
    ],
    planner_chapter_destination: "chapter_daily_coordination",
    relevant_ten_god_expressions: ["식신/상관 (미식/문화/취미 향유)", "편재 (새로운 경험 탐색)"],
    support_classification: "SUPPORTABLE_NOW",
  },

  friend_repair_reconciliation: {
    lens_id: "friend_repair_reconciliation",
    domain: "friend",
    user_question_ko: "사소한 말실수나 약속 펑크로 삐쳤을 때 쿨하게 풀고 웃어넘기는 화해법은?",
    user_question_en: "How to defuse momentary misunderstandings or cancelled plans with humor and no lingering grudges?",
    required_personal_ce_a: ["conflict_response", "recovery_decompression_style"],
    required_personal_ce_b: ["conflict_response", "recovery_decompression_style"],
    required_pair_ce_meanings: ["repair_entry_point", "repair_loop"],
    supporting_raw_saju_facts: ["cross_hits.stem_clash", "cross_hits.branch_six_combine"],
    directional_status: "symmetric",
    minimum_evidence_threshold: "Stem clash or branch combine hit",
    corroborating_evidence: ["Food god humor buffer", "Element flow"],
    contradiction_handling: "Defuse immediately via memes/casual dining without heavy emotional confrontation",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no clash or combine hits",
    confidence_rule: "high if stem clash + branch combine; medium if clash only",
    canonical_meaning_variants: [
      { variant_id: "friend_repair_humor_defuse", description_ko: "유머 섞인 카톡이나 가벼운 술자리로 어색함을 녹이는 화해", evidence_trigger: "Stem clash hit" },
      { variant_id: "friend_repair_natural_reset", description_ko: "자연스럽게 다시 대화를 이어가며 무던하게 넘어가는 리셋", evidence_trigger: "No clash hits" },
      { variant_id: "friend_repair_insufficient_evidence", description_ko: "친구 화해 지표 부족", evidence_trigger: "No hits" },
    ],
    planner_chapter_destination: "chapter_friction_repair",
    relevant_ten_god_expressions: ["식신 (유머와 음식으로 풀기)", "비견 (뒤끝 없는 쿨한 사과)"],
    support_classification: "SUPPORTABLE_AFTER_PAIR_CE_ENHANCEMENT",
  },

  // ==========================================================================
  // WORK COLLEAGUE DOMAIN (8 LENSES)
  // ==========================================================================
  work_leadership_split: {
    lens_id: "work_leadership_split",
    domain: "work",
    user_question_ko: "프로젝트를 리드할 때 대외적 방향 결정과 내부 실행 조율은 어떻게 나눌까?",
    user_question_en: "How should external strategic vision and internal operational execution be divided between the colleagues?",
    required_personal_ce_a: ["leadership_responsibility", "decision_pace"],
    required_personal_ce_b: ["leadership_responsibility", "decision_pace"],
    required_pair_ce_meanings: ["role_formation", "directional_support_exchange"],
    supporting_raw_saju_facts: ["cross_hits.stem_combine", "element_flow.direction"],
    directional_status: "directional",
    minimum_evidence_threshold: "Stem combine or element flow direction",
    corroborating_evidence: ["Personal officer star distribution", "Day master strength"],
    contradiction_handling: "Both strong leaders -> divide by domain (external/strategy vs internal/roadmap)",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no combine and null element flow",
    confidence_rule: "high if stem combine + element flow; medium if flow only",
    canonical_meaning_variants: [
      { variant_id: "work_leadership_co_architect", description_ko: "전략적 비전과 치밀한 운영이 결합된 원팀 리더십", evidence_trigger: "Stem combine hit" },
      { variant_id: "work_leadership_division", description_ko: "영역별 전문성을 상호 존중하는 역할 분담", evidence_trigger: "No combine hits / directional flow" },
      { variant_id: "work_leadership_insufficient_evidence", description_ko: "리더십 분담 지표 부족", evidence_trigger: "No relevant hits" },
    ],
    planner_chapter_destination: "chapter_core_resonance",
    relevant_ten_god_expressions: ["정관/편관 (비전 제시 및 총괄)", "정재/상관 (실행 로드맵 및 운영)"],
    support_classification: "SUPPORTABLE_NOW",
  },

  work_task_execution: {
    lens_id: "work_task_execution",
    domain: "work",
    user_question_ko: "실제 업무를 쳐낼 때 마일스톤 관리와 마감 기한 핸드오프는 어떻게 맞출까?",
    user_question_en: "How to synchronize milestone handoffs and deadline accountability like clockwork?",
    required_personal_ce_a: ["structure_spontaneity_preference", "decision_pace"],
    required_personal_ce_b: ["structure_spontaneity_preference", "decision_pace"],
    required_pair_ce_meanings: ["role_formation", "resource_responsibility_exchange"],
    supporting_raw_saju_facts: ["cross_hits.branch_six_combine", "trio_hits"],
    directional_status: "symmetric",
    minimum_evidence_threshold: "Branch combine or trio hit",
    corroborating_evidence: ["Wealth star in both charts", "Element harmony"],
    contradiction_handling: "Define explicit Definition of Done (DoD) to eliminate handoff drops",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no branch combine hits",
    confidence_rule: "high if branch combine/trio; medium if single combine",
    canonical_meaning_variants: [
      { variant_id: "work_execution_milestone_sync", description_ko: "마일스톤별 인수인계가 톱니바퀴처럼 맞아떨어지는 실행 시너지", evidence_trigger: "Branch combine hit" },
      { variant_id: "work_execution_handoff_protocol", description_ko: "명확한 완료 조건(DoD)을 문서화하여 누수를 방지하는 핸드오프", evidence_trigger: "No combine hits" },
      { variant_id: "work_execution_insufficient_evidence", description_ko: "업무 실행 지표 부족", evidence_trigger: "No hits" },
    ],
    planner_chapter_destination: "chapter_daily_coordination",
    relevant_ten_god_expressions: ["정재 (치밀한 마감 준수)", "정관 (프로세스 관리)"],
    support_classification: "SUPPORTABLE_NOW",
  },

  work_feedback_cushion: {
    lens_id: "work_feedback_cushion",
    domain: "work",
    user_question_ko: "코드 리뷰나 성과 피드백을 주고받을 때 감정 상하지 않고 핵심을 전하는 톤은?",
    user_question_en: "How to deliver technical critique and code reviews without triggering personal defensiveness?",
    required_personal_ce_a: ["criticism_sensitivity", "expression_signaling_style"],
    required_personal_ce_b: ["criticism_sensitivity", "expression_signaling_style"],
    required_pair_ce_meanings: ["conflict_activation_pattern", "misunderstanding_translation"],
    supporting_raw_saju_facts: ["cross_hits.stem_clash", "cross_hits.branch_clash"],
    directional_status: "dual_polarity",
    minimum_evidence_threshold: "Stem clash or branch clash hit",
    corroborating_evidence: ["Personal officer star excess", "Day branch tension"],
    contradiction_handling: "Separate code critique from personal ego with objective evidence and alternative solutions",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no clash hits exist",
    confidence_rule: "high if stem clash; medium if branch clash only",
    canonical_meaning_variants: [
      { variant_id: "work_feedback_objective_cushion", description_ko: "사람이 아닌 문제에 집중하고 구체적 대안을 제시하는 객관적 피드백", evidence_trigger: "Stem clash hit" },
      { variant_id: "work_feedback_constructive_tone", description_ko: "자연스럽게 개선점을 수용하고 발전시키는 온화한 피드백 교환", evidence_trigger: "No clash hits" },
      { variant_id: "work_feedback_insufficient_evidence", description_ko: "피드백 조율 지표 부족", evidence_trigger: "No tension evidence" },
    ],
    planner_chapter_destination: "chapter_friction_repair",
    relevant_ten_god_expressions: ["상관 (비판적 검토/톤 완화 필요)", "정인 (수용적 성장 마인드셋)"],
    support_classification: "SUPPORTABLE_AFTER_PAIR_CE_ENHANCEMENT",
  },

  work_micromanage_guard: {
    lens_id: "work_micromanage_guard",
    domain: "work",
    user_question_ko: "과도한 간섭이나 불필요한 보고 없이 신뢰 기반의 자율성을 보장하는 법은?",
    user_question_en: "How to prevent micromanagement and preserve high-trust autonomous execution?",
    required_personal_ce_a: ["leadership_responsibility", "solitude_autonomy_need"],
    required_personal_ce_b: ["autonomy_need", "criticism_sensitivity"],
    required_pair_ce_meanings: ["closeness_versus_space_mismatch", "role_formation"],
    supporting_raw_saju_facts: ["cross_hits.wonjin_guimun", "cross_hits.gongmang"],
    directional_status: "symmetric",
    minimum_evidence_threshold: "Wonjin/Guimun or gongmang hit",
    corroborating_evidence: ["Officer star tension", "Day branch isolation"],
    contradiction_handling: "Replace status meetings with asynchronous tickets and outcome-based milestones",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if no wonjin/gongmang",
    confidence_rule: "high if day wonjin; medium if other pillars",
    canonical_meaning_variants: [
      { variant_id: "work_autonomy_trust_ownership", description_ko: "과정 간섭을 줄이고 명확한 마일스톤 결과물로 평가하는 신뢰 자율성", evidence_trigger: "Wonjin / Guimun hit" },
      { variant_id: "work_autonomy_natural_freedom", description_ko: "자연스럽게 서로의 역량을 신뢰하며 일하는 편안한 자율성", evidence_trigger: "No wonjin hits" },
      { variant_id: "work_autonomy_insufficient_evidence", description_ko: "자율성 관리 지표 부족", evidence_trigger: "No relevant hits" },
    ],
    planner_chapter_destination: "chapter_core_resonance",
    relevant_ten_god_expressions: ["편인 (독립적 몰입 환경)", "편관 (간섭 스트레스 완화)"],
    support_classification: "SUPPORTABLE_NOW",
  },

  work_stress_reaction: {
    lens_id: "work_stress_reaction",
    domain: "work",
    user_question_ko: "장애 발생이나 납기 압박 등 극한의 스트레스 상황에서 충돌을 막는 법은?",
    user_question_en: "How to maintain blameless incident response and coordinated teamwork under production outages?",
    required_personal_ce_a: ["pressure_response", "conflict_response"],
    required_personal_ce_b: ["pressure_response", "conflict_response"],
    required_pair_ce_meanings: ["pressure_amplification_or_buffering", "conflict_activation_pattern"],
    supporting_raw_saju_facts: ["cross_hits.branch_clash", "cross_hits.branch_punishment"],
    directional_status: "dual_polarity",
    minimum_evidence_threshold: "Branch clash or punishment hit",
    corroborating_evidence: ["Stem clash", "Excessive fire/water johu tension"],
    contradiction_handling: "Execute blameless rollback first; schedule retrospective only after service is stabilized",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no branch clash/punishment hits",
    confidence_rule: "high if day branch clash; medium if month/year clash",
    canonical_meaning_variants: [
      { variant_id: "work_stress_calm_anchor", description_ko: "위기 시 책임 공방을 멈추고 롤백 및 사후 회고에 집중하는 안전장치", evidence_trigger: "Branch clash / punishment hit" },
      { variant_id: "work_stress_cooperative_rally", description_ko: "침착하게 역할을 분담하며 일사불란하게 위기를 돌파하는 팀워크", evidence_trigger: "No clash hits" },
      { variant_id: "work_stress_insufficient_evidence", description_ko: "위기 대응 지표 부족", evidence_trigger: "No tension hits" },
    ],
    planner_chapter_destination: "chapter_friction_repair",
    relevant_ten_god_expressions: ["편관 (위기 상황의 침착한 결단)", "정인 (심리적 안정감 제공)"],
    support_classification: "SUPPORTABLE_AFTER_PAIR_CE_ENHANCEMENT",
  },

  work_decision_style: {
    lens_id: "work_decision_style",
    domain: "work",
    user_question_ko: "데이터 기반 분석과 직관적 빠른 실행 사이의 의사결정 방식 충돌은?",
    user_question_en: "How do data-driven validation and intuitive rapid execution balance each other in decision making?",
    required_personal_ce_a: ["decision_pace_style", "structure_spontaneity_preference"],
    required_personal_ce_b: ["decision_pace_style", "structure_spontaneity_preference"],
    required_pair_ce_meanings: ["decision_coordination_flow"],
    supporting_raw_saju_facts: ["element_flow.interaction_code", "element_flow.direction"],
    directional_status: "directional",
    minimum_evidence_threshold: "Element flow direction or personal decision profiles",
    corroborating_evidence: ["Wealth/Officer vs Food/Kill contrast", "Twelve stage pace"],
    contradiction_handling: "Synthesize rapid experimentation with rigorous metric evaluation",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if element flow null and personal profiles identical",
    confidence_rule: "high if element flow clear; medium if balanced",
    canonical_meaning_variants: [
      { variant_id: "work_decision_balanced_heuristics", description_ko: "가설 검증의 속도와 데이터 분석의 정밀함이 균형을 잡는 의사결정", evidence_trigger: "Element flow present" },
      { variant_id: "work_decision_aligned_pace", description_ko: "비슷한 호흡과 판단 기준을 공유하는 신속한 의사결정", evidence_trigger: "Element same or gentle flow" },
      { variant_id: "work_decision_insufficient_evidence", description_ko: "의사결정 스타일 지표 부족", evidence_trigger: "No relevant data" },
    ],
    planner_chapter_destination: "chapter_daily_coordination",
    relevant_ten_god_expressions: ["정재/정관 (데이터/리스크 검증)", "편재/식상 (신속한 가설 실험)"],
    support_classification: "SUPPORTABLE_AFTER_PERSONAL_CE_ENHANCEMENT",
  },

  work_special_weapon: {
    lens_id: "work_special_weapon",
    domain: "work",
    user_question_ko: "둘이 뭉쳤을 때 어떤 프로젝트나 과제도 뚫어내는 둘만의 필살 무기는?",
    user_question_en: "What complementary superpower allows the pair to break through high-complexity technical blockers?",
    required_personal_ce_a: ["talent_expression_channel", "leadership_responsibility"],
    required_personal_ce_b: ["talent_expression_channel", "leadership_responsibility"],
    required_pair_ce_meanings: ["stable_bonding_resources", "directional_support_exchange"],
    supporting_raw_saju_facts: ["cross_hits.branch_six_combine", "trio_hits", "cross_hits.stem_combine"],
    directional_status: "symmetric",
    minimum_evidence_threshold: "Branch combine, stem combine, or trio hit",
    corroborating_evidence: ["Yongsin alignment", "Noble stars"],
    contradiction_handling: "Combine strengths to cover mutual blind spots seamlessly",
    unknown_hour_dependency: "low_impact",
    abstention_rule: "Abstain if no combine hits exist",
    confidence_rule: "high if branch combine/trio; medium if stem combine only",
    canonical_meaning_variants: [
      { variant_id: "work_synergy_cross_functional_power", description_ko: "기획력과 실행력이 결합되어 불가능한 납기도 뚫어내는 전사적 시너지", evidence_trigger: "Branch combine / trio hit" },
      { variant_id: "work_synergy_reliable_execution", description_ko: "각자의 역할을 우직하게 완수하여 끝내 목표를 달성하는 견고한 협업", evidence_trigger: "Stem combine or yongsin overlap" },
      { variant_id: "work_synergy_insufficient_evidence", description_ko: "시너지 무기 지표 부족", evidence_trigger: "No combine hits" },
    ],
    planner_chapter_destination: "chapter_core_resonance",
    relevant_ten_god_expressions: ["식상생재 (기획과 사업화)", "관인상생 (체계적 확장과 조직화)"],
    support_classification: "SUPPORTABLE_NOW",
  },

  work_burnout_recovery: {
    lens_id: "work_burnout_recovery",
    domain: "work",
    user_question_ko: "업무 과부하나 번아웃이 왔을 때 서로를 지치지 않게 지탱해 주는 회복법은?",
    user_question_en: "How do colleagues proactively rebalance tasks and protect sustainable pacing against burnout?",
    required_personal_ce_a: ["pressure_response", "recovery_decompression_style"],
    required_personal_ce_b: ["pressure_response", "recovery_decompression_style"],
    required_pair_ce_meanings: ["pressure_amplification_or_buffering", "stable_bonding_resources"],
    supporting_raw_saju_facts: ["cross_hits.branch_six_combine", "element_flow"],
    directional_status: "dual_polarity",
    minimum_evidence_threshold: "Branch combine or supportive element flow",
    corroborating_evidence: ["Temperature complement", "Noble star presence"],
    contradiction_handling: "Proactive task rebalancing before emotional fatigue peaks",
    unknown_hour_dependency: "none",
    abstention_rule: "Abstain if no supportive combine or flow",
    confidence_rule: "high if branch combine + element flow; medium if one hit only",
    canonical_meaning_variants: [
      { variant_id: "work_burnout_sustainable_pacing", description_ko: "동료의 과부하를 먼저 알아채고 업무를 백업해 주는 성숙한 동료애", evidence_trigger: "Branch combine hit" },
      { variant_id: "work_burnout_mutual_encouragement", description_ko: "커피 한잔과 따뜻한 응원으로 지친 일상에 활력을 불어넣는 쉼표", evidence_trigger: "Element flow / gentle support" },
      { variant_id: "work_burnout_insufficient_evidence", description_ko: "번아웃 회복 지표 부족", evidence_trigger: "No supportive hits" },
    ],
    planner_chapter_destination: "chapter_friction_repair",
    relevant_ten_god_expressions: ["정인 (심리적 안정과 배려)", "비견 (든든한 업무 백업)"],
    support_classification: "SUPPORTABLE_AFTER_PAIR_CE_ENHANCEMENT",
  },
};
