/**
 * Sprint 5/6 — 30-second Premium Overview projector.
 * Restores legacy's header gauges (meta.event_scores) into V2. Supplies raw
 * numbers only — label mapping (emoji/text) happens at render time via
 * useMessages(), the same split already used by projectHorizon /
 * RomanticHorizonSection, since a projector is a plain function and cannot
 * call a React hook.
 * Sprint 6: dropped the legacy snapshot-panel read (resolveSnapshotPanelFromReport)
 * — that content is generated by legacy's rule-screen-plan pipeline, not
 * guaranteed to run for pure-V2 reports, and its copy predates the current
 * Blueprint vocabulary. The section below the gauges now reuses vm.snapshot
 * (Product Bible / Romantic Blueprint M2 signals) instead — see
 * RomanticPremiumOverviewSection. No new analysis: event_scores is already
 * computed server-side and already present on the report type.
 */
import type { RomanticSajuDeepReport } from "@/lib/prompts/relationshipPremium/romanticSajuDeep/outputSchema";
import type {
  ConfidenceLevel,
  EvidenceRef,
  PremiumOverviewVM,
} from "../romanticExperienceTypes";
import { emptyPremiumOverview } from "./_empty";

export type ProjectPremiumOverviewInput = {
  report: RomanticSajuDeepReport["report"];
};

export function projectPremiumOverview(
  input: ProjectPremiumOverviewInput,
): PremiumOverviewVM {
  const base = emptyPremiumOverview();
  const meta = input.report.meta as
    | { event_scores?: { overall?: { activation: number; benefit: number; risk: number } } }
    | undefined;
  const overall = meta?.event_scores?.overall;
  const eventScores =
    overall &&
    Number.isFinite(overall.activation) &&
    Number.isFinite(overall.benefit) &&
    Number.isFinite(overall.risk)
      ? { activation: overall.activation, benefit: overall.benefit, risk: overall.risk }
      : null;

  if (!eventScores) return base;

  const evidence: EvidenceRef[] = [
    { path: "meta.event_scores.overall", summary: "activation/benefit/risk gauges" },
  ];

  return {
    available: true,
    confidence: "medium" as ConfidenceLevel,
    evidence,
    eventScores,
  };
}
